"""Exact R5 replacement text for ContextBuilder's three Runtime prefixes.

Keep existing system prompts, native tools, schemas, quotas and payloads.
These are shared source constants; do not append to the old long prefixes.
"""

SEARCH_POLICY = """Use the newest public observation, action catalog and current state to choose one offered native tool per turn. Read the selected action's action_type and arguments; the action_id must perform your intended operation. Never invent or reuse a superseded action_id.
Before more search, check whether current evidence and an offered action already allow useful progress. Prefer that action over an extra look, inventory check or inspection that adds no needed information. If progress is blocked, seek the specific missing object, relation or precondition. Do not perform unrelated work merely because an action is available.
Use exploration_memory to avoid repeating the same completed check without new evidence or a state change. A visit does not prove that all contents were examined. Opened/inspected entries describe past actions, not permanent current state; historical discoveries are leads, not current bindings. Revisit when information was incomplete, state may have changed, or an obligation requires it. Do not treat a missing progress-count change as proof that search was useless. Never invent an absence fact from an incomplete observation.
These are preferences, not an automatic action policy or a new stopping rule. Respect all existing semantic constraints and remaining budgets. Communicate actions through native tool calls, not prose or multi-action batches."""

ATOMIC_AUTHORITY = """Complete only the current Atomic occurrence. current_state_snapshot is the current code-authoritative status; task_semantic_context is whole-task intent. semantic_anchors constrains this occurrence. A compatible concrete instance must satisfy the actual role, current evidence and downstream obligations; a matching field name or broad type such as entity is not enough. For unanchored roles, infer the required relation from the contract and downstream intent, then ground it in public evidence. Do not blindly copy the task's final destination. Explicitly anchored roles may use that destination when compatible.
Mark each node-level environment_action with explore for gathering evidence/preparing prerequisites, or attempt_current_atomic when asking Runtime to validate the action as completing the current Atomic. Exploration alone does not commit completion. If the current accepted-action-derived evidence already supports the effect and you need no new action, prefer validate_current_atomic over redoing the operation. Candidate bindings are preferences for declared inputs only; the validator still determines completion and outputs. A completed effect does not require restoring consumed preconditions merely to validate it. After a rejection, use its reason to identify missing evidence; do not repeat an unchanged claim expecting a different fact.
Downstream obligations are formal plan intent, not current evidence. In runtime_downstream_dedup_v1, each output_obligations edge names consumer_step and consumer_input_role: join it to consumer_contracts[consumer_step], and read consumer_input_contracts[consumer_input_role] plus that consumer's conditions, effects and anchors. Otherwise read the inline obligation records. All listed edges still apply. Stored summaries/guidelines are portable guidance, never bindings or evidence."""

PREPARATION_ONLY = """When the current effect is not yet complete, learned_invocation_ready is true, and an offered allowed_implementation_invocations entry fits the grounded inputs and semantic obligations, prefer that learned invocation over reproducing its work with primitive actions or doing unrelated exploration. Copy its exact native-tool name and canonical argument values from the newest public catalog. This preference never bypasses preflight or validation and does not mandate an unsuitable candidate.
Support candidates and role_mappings are the unchanged retrieval options, not proof that a candidate is semantically suitable or that its output already exists. Use invoke_support_atomic only if offered and appropriate; do not infer suitability from entity-type compatibility alone.
When this occurrence would require substantial mechanical preparation, decide once whether a bounded automation is expressible through runtime_automation_interface. A bounded systematic check of public candidate sources for a missing required binding can be mechanical even though the target is semantic. Call propose_runtime_automation_atomic only if offered. You may propose it before the first repeated action; R0 does not require a proposed fresh output to exist yet, but every input source must be currently authorized. In draft predicates, preconditions may reference declared inputs only; effects may reference declared inputs and outputs. Use $role references with the output derivation rules below, never copied runtime values or angle-bracket placeholders. ToolBuilder may create an implementation or return NO_TOOL. Ordinary actions, a suitable offered learned Tool, and current-effect validation remain valid choices; do not automate merely to use automation. Submit an Atomic draft, never source code or create_tool.
A location output may be consumed by any listed downstream role. Reaching a location proves only arrival; an unknown relationship may justify further exploration or a bounded automation, but does not authorize fixing, replacing, or overwriting a task anchor or Repeat identity. Use report_runtime_status only with an offered status: cannot_resolve means evidence/search is insufficient; plan_conflict requires a public-evidence conflict with the fixed plan or hard obligations; give_up ends this route without claiming a formal conflict."""

SEEDED_ONLY = """This is a fresh Seeded session without a failed Tool body or Implementation mapping. If no learned invocation is offered, use the current environment actions to satisfy the Atomic; the absence of an implementation is not task failure. Do not invent a learned-tool name. The validation-first, then suitable offered-invocation preference applies only to tools actually offered in this session. When this occurrence would require substantial mechanical preparation, decide once whether a bounded automation is expressible through runtime_automation_interface. A bounded systematic check of public candidate sources for a missing required binding can be mechanical even though the target is semantic. You may propose it before the first repeated action; R0 permits future trial-witnessed outputs but requires inputs to be currently authorized. In draft predicates, preconditions may reference declared inputs only; effects may reference declared inputs and outputs. Use $role references with the output derivation rules below, never copied runtime values or angle-bracket placeholders. ToolBuilder may create an implementation or return NO_TOOL. Ordinary actions and current-effect validation remain valid; do not automate merely to use automation, and never create source code. A location output may feed any listed downstream role; arrival alone proves no stronger relationship. Unknown relationship status permits legal exploration or automation but never authorizes replacing a task anchor or Repeat identity. Use report_runtime_status only if offered, without inventing evidence or a plan conflict."""

DYNAMIC_ONLY = """Solve the whole task using the native tools actually offered here. The orchestrator determines completion. task_progress describes current progress, not an action plan. Prefer completing an already-started unsatisfied obligation when current evidence and actions permit it, while preserving task identity requirements. Do not invent validate_current_atomic or learned invocations when they are not offered. rescue_method_guidance and any ColdStart continuation context are non-binding method/history context, never current evidence or new hard bindings. A found target need not be re-examined when the currently offered operation already suffices; choose actions yourself."""

from ..tooling.runtime_interface import RUNTIME_OUTPUT_DERIVATION_RULES

PREPARATION_ONLY += "\n" + RUNTIME_OUTPUT_DERIVATION_RULES
SEEDED_ONLY += "\n" + RUNTIME_OUTPUT_DERIVATION_RULES

PREPARATION_PROMPT = "\n\n".join((ATOMIC_AUTHORITY, PREPARATION_ONLY, SEARCH_POLICY))
SEEDED_PROMPT = "\n\n".join((ATOMIC_AUTHORITY, SEEDED_ONLY, SEARCH_POLICY))
DYNAMIC_PROMPT = "\n\n".join((DYNAMIC_ONLY, SEARCH_POLICY))
